#=
TOML — read/write .materialdocs.toml configuration files.

The .materialdocs.toml file is the bridge between the live theme editor and
the build system. The editor writes it; Material3() reads it at build time.
Users can also hand-edit it directly.

Format:
    [theme]
    name = "my-theme"
    seed = "#1565C0"
    secondary_seed = "#00897B"   # optional
    tertiary_seed = "#E65100"    # optional

    [theme.fonts]
    display = "Fira Sans"
    body = "Source Sans 3"
    code = "JetBrains Mono"

    [theme.shape]
    corner_radius = "rounded"    # sharp | slight | rounded | full

    [theme.custom_colors]        # optional overrides
    primary = "#custom-hex"
=#

import TOML

"""
    load_theme(path::String) → ThemeConfig

Load a theme from a `.materialdocs.toml` file. Returns a `ThemeConfig` with
all fields populated (missing fields use defaults).

Throws `ArgumentError` if the file cannot be parsed or contains invalid values.
"""
function load_theme(path::String)::ThemeConfig
    isfile(path) || throw(ArgumentError("Theme file not found: $path"))

    local data
    try
        data = TOML.parsefile(path)
    catch e
        throw(ArgumentError("Failed to parse TOML file $path: $(sprint(showerror, e))"))
    end

    theme = get(data, "theme", Dict{String,Any}())
    theme isa Dict || throw(ArgumentError("Expected [theme] table in $path"))

    # Basic fields
    name = get(theme, "name", "custom")::String
    seed = get(theme, "seed", "#6750A4")::String
    _validate_hex(seed, "seed", path)

    secondary_seed = get(theme, "secondary_seed", nothing)
    if secondary_seed !== nothing
        secondary_seed = String(secondary_seed)
        _validate_hex(secondary_seed, "secondary_seed", path)
    end

    tertiary_seed = get(theme, "tertiary_seed", nothing)
    if tertiary_seed !== nothing
        tertiary_seed = String(tertiary_seed)
        _validate_hex(tertiary_seed, "tertiary_seed", path)
    end

    # Fonts
    fonts = get(theme, "fonts", Dict{String,Any}())
    fonts isa Dict || throw(ArgumentError("Expected [theme.fonts] table in $path"))
    display_font = get(fonts, "display", "Roboto")::String
    body_font = get(fonts, "body", "Roboto")::String
    code_font = get(fonts, "code", "Roboto Mono")::String

    # Shape
    shape = get(theme, "shape", Dict{String,Any}())
    shape isa Dict || throw(ArgumentError("Expected [theme.shape] table in $path"))
    corner_str = get(shape, "corner_radius", "rounded")::String
    corner_radius = Symbol(corner_str)
    if corner_radius ∉ (:sharp, :slight, :rounded, :full)
        throw(ArgumentError("Invalid corner_radius \"$corner_str\" in $path — expected sharp, slight, rounded, or full"))
    end

    # Custom colors
    custom_colors_raw = get(theme, "custom_colors", Dict{String,Any}())
    custom_colors_raw isa Dict || throw(ArgumentError("Expected [theme.custom_colors] table in $path"))
    custom_colors = Dict{String,String}()
    for (k, v) in custom_colors_raw
        vstr = String(v)
        _validate_hex(vstr, "custom_colors.$k", path)
        custom_colors[String(k)] = vstr
    end

    ThemeConfig(;
        name,
        seed,
        secondary_seed,
        tertiary_seed,
        display_font,
        body_font,
        code_font,
        corner_radius,
        custom_colors,
    )
end

"""
    save_theme(config::ThemeConfig, path::String)

Write a `ThemeConfig` to a `.materialdocs.toml` file. Overwrites any existing
file at `path`. The output is a clean, human-readable TOML file.
"""
function save_theme(config::ThemeConfig, path::String)
    io = IOBuffer()

    println(io, "# .materialdocs.toml")
    println(io, "# Generated by MaterialDocs.jl — edit freely")
    println(io)
    println(io, "[theme]")
    println(io, "name = ", _toml_str(config.name))
    println(io, "seed = ", _toml_str(config.seed))

    if config.secondary_seed !== nothing
        println(io, "secondary_seed = ", _toml_str(config.secondary_seed))
    end
    if config.tertiary_seed !== nothing
        println(io, "tertiary_seed = ", _toml_str(config.tertiary_seed))
    end

    println(io)
    println(io, "[theme.fonts]")
    println(io, "display = ", _toml_str(config.display_font))
    println(io, "body = ", _toml_str(config.body_font))
    println(io, "code = ", _toml_str(config.code_font))

    println(io)
    println(io, "[theme.shape]")
    println(io, "corner_radius = ", _toml_str(String(config.corner_radius)))

    if !isempty(config.custom_colors)
        println(io)
        println(io, "[theme.custom_colors]")
        for (k, v) in sort!(collect(config.custom_colors))
            println(io, k, " = ", _toml_str(v))
        end
    end

    # Ensure parent directory exists
    dir = dirname(path)
    !isempty(dir) && !isdir(dir) && mkpath(dir)

    Base.write(path, String(take!(io)))
end

"""
    find_theme_toml(docs_dir::String) → Union{String, Nothing}

Search for a `.materialdocs.toml` file in the given directory. Returns the
absolute path if found, or `nothing`.
"""
function find_theme_toml(docs_dir::String)::Union{String,Nothing}
    candidates = [
        joinpath(docs_dir, ".materialdocs.toml"),
        joinpath(docs_dir, "materialdocs.toml"),
    ]
    for path in candidates
        isfile(path) && return path
    end
    nothing
end

# ─────────────────────────────────────────────────────────────────────────────
# Internal helpers
# ─────────────────────────────────────────────────────────────────────────────

"""Validate a hex color string."""
function _validate_hex(hex::String, field::String, path::String)
    if !occursin(r"^#[0-9A-Fa-f]{6}$", hex)
        throw(ArgumentError("Invalid hex color \"$hex\" for $field in $path"))
    end
end

"""Format a string as a TOML quoted string."""
function _toml_str(s::String)::String
    # TOML basic strings use double quotes; escape special chars
    escaped = replace(s,
        '\\' => "\\\\",
        '"' => "\\\"",
        '\n' => "\\n",
        '\t' => "\\t",
    )
    "\"$escaped\""
end
